version: 1.0.{build}
environment:
  OPENSSL_VERSION: 1.0.2o
pull_requests:
  do_not_increment_build_number: true
configuration: Release
platform: x64
clone_folder: C:\projects\myproject
init:
- cmd: git config --global core.autocrlf input
clone_script:
- cmd: "git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER% \ncd %APPVEYOR_BUILD_FOLDER%\ngit checkout -q %APPVEYOR_REPO_COMMIT%\ngit submodule update --init --recursive"
install:
- ps: |
    Remove-Item C:\OpenSSL-Win32 -Force -Recurse
    Remove-Item C:\OpenSSL-Win64 -Force -Recurse

    $version = $env:OPENSSL_VERSION -replace '\.', '_'
    Start-FileDownload "https://slproweb.com/download/Win64OpenSSL-$version.exe"

    $file = ".\Win64OpenSSL-$version.exe"
    $hash = '2f40679fc0be1c3d2d6affafa72a1776635716ee705d4f8cac8f9a219e66d377'
    if ($hash -ne (Get-FileHash -Path $file -Algorithm SHA256).Hash) {
      throw 'Invalid file hash'
    }

    Start-Process -FilePath $file -ArgumentList '/SP-','/VERYSILENT','/SUPPRESSMSGBOXES','/NORESTART' -NoNewWindow -Wait

- cmd: >-
    SET GIT_COMMIT=%APPVEYOR_REPO_COMMIT:~0,3%

    cmake -DDISABLE_NATIVE_ARCH=ON -DRAIBLOCKS_SECURE_RPC=ON -DBOOST_ROOT=C:/Libraries/boost_1_66_0 -G "Visual Studio 14 2015 Win64" -DIPHLPAPI_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/iphlpapi.lib" -DWINSOCK2_LIBRARY="C:/Program Files (x86)/Windows Kits/10/Lib/10.0.14393.0/um/x64/WS2_32.lib" -DGIT_COMMIT=%GIT_COMMIT%

- ps: >-
    $size_t=select-string -path ".\bootstrap_weights.cpp" -Pattern "rai_bootstrap_weights_size"| foreach {$_.Line}
    
    $old_size_t = "extern const size_t rai_bootstrap_weights_size;"
    
    $char=select-string -path ".\bootstrap_weights.cpp" -Pattern "char rai_bootstrap_weights"| foreach {$_.Line}
    
    $old_char = [regex]::Escape("extern const char rai_bootstrap_weights[];") 
    
    select-string -path ".\rai\node\node.cpp" -Pattern $old_size_t -SimpleMatch | %{$curpath=$_.path; (get-content $curpath -Raw) -replace $old_char, $char| Out-File $curpath}
    
    select-string -path ".\rai\node\node.cpp" -Pattern $old_size_t -SimpleMatch | %{$curpath=$_.path; (get-content $curpath -Raw) -replace $old_size_t, $size_t| Out-File $curpath}

build:
  parallel: true  
  project: rai_node.vcxproj
  verbosity: detailed
after_build:
- cmd: 7z a -tzip -mx=9 node-win32.zip "%APPVEYOR_BUILD_FOLDER%/Release/rai_node.exe"
artifacts:
- path: node-win32.zip
  name: node-win32
